---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - echo "starting the test of the eduroam role"
#  - cd roles/eduroam/
  # doing a simplesntax check of the role
  - ansible-playbook -i inventory one.yml --syntax-check
#  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # now, try to execute the role under test conditions
 # - ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook -i inventory one.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
