---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # doing a simplesntax check of the role
  - ansible-playbook -i inventory one.yaml --syntax-check
  # now, try to execute the role under test conditions
  - ansible-playbook -i inventory one.yaml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
